/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.1_@babel+parse_be9b2986a85d20b9d8f5f213e5d32702/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.1_@babel+parse_be9b2986a85d20b9d8f5f213e5d32702/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCalendar: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.1_@babel+parse_be9b2986a85d20b9d8f5f213e5d32702/node_modules/@nuxt/ui/dist/runtime/components/Calendar.vue')['default']
    UCheckbox: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.1_@babel+parse_be9b2986a85d20b9d8f5f213e5d32702/node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UFormField: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.1_@babel+parse_be9b2986a85d20b9d8f5f213e5d32702/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.1_@babel+parse_be9b2986a85d20b9d8f5f213e5d32702/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.1_@babel+parse_be9b2986a85d20b9d8f5f213e5d32702/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    ULink: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.1_@babel+parse_be9b2986a85d20b9d8f5f213e5d32702/node_modules/@nuxt/ui/dist/runtime/inertia/components/Link.vue')['default']
    ULinkBase: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.1_@babel+parse_be9b2986a85d20b9d8f5f213e5d32702/node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue')['default']
    UNavigationMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.1_@babel+parse_be9b2986a85d20b9d8f5f213e5d32702/node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    UPopover: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.1_@babel+parse_be9b2986a85d20b9d8f5f213e5d32702/node_modules/@nuxt/ui/dist/runtime/components/Popover.vue')['default']
    USelect: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.1_@babel+parse_be9b2986a85d20b9d8f5f213e5d32702/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USeparator: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.1_@babel+parse_be9b2986a85d20b9d8f5f213e5d32702/node_modules/@nuxt/ui/dist/runtime/components/Separator.vue')['default']
    UStepper: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.1_@babel+parse_be9b2986a85d20b9d8f5f213e5d32702/node_modules/@nuxt/ui/dist/runtime/components/Stepper.vue')['default']
    UTabs: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.1_@babel+parse_be9b2986a85d20b9d8f5f213e5d32702/node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
  }
}
